### ISSUE TITLE
Julia Registry?

### ISSUE THREAD

**Issue by captchanjack** [emmt/QuickHeaps.jl#1]
Hello! Nice package :)

Any chance you are going to push this to the general Julia Registry?

**Comment by emmt** [comment]
Hello, thank you for your support. I hesitated to put this package in the General registry because of the overlapping with `DataStructure` and a merging would probably require a lot of work. If you think this can be useful for you (and perhaps others) I can submit `QuickHeaps` to General registry.

**Comment by captchanjack** [comment]
Looks like I can get better performance using your package vs DataStructures.jl

Would be much appreciated if you could submit this to General! Thanks

**Comment by emmt** [comment]
OK I'll do that. It will take a few days before this is accepted...

**Comment by emmt** [comment]
OK this is done: starting with version 0.1.1,  [QuickHeaps](https://github.com/emmt/QuickHeaps.jl) is in Julia's General registry.
